version: '3'
services:
  prisma:
    container_name: prisma_graphql_1
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "6789:6789"
    environment:
      PRISMA_CONFIG: |
        port: 6789
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    container_name: prisma_mysql_1
    image: mysql:5.7
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - /Users/threem0126/Desktop/mysql_datadir:/var/lib/mysql 